In [1]:
import pandas as pd
import numpy as np
import datetime

# Data is measured in thousands of pounds, worldwide
# Therefore, transforming pounds into kg and adjusting to Mexico's export percentage is necessary

poundsToKg = 0.453592
shareMexico = 0.888

# Import volume of avocados imported by the US

df = pd.read_excel(r'TradeTables.xlsx', 'ImpVol')

# Data munging

df = df.iloc[4:10, 3:21].drop(['Unnamed: 5', 'Unnamed: 8', 'Unnamed: 11',
                         'Unnamed: 13', 'Unnamed: 17'], axis = 1)
df = df.set_index('Unnamed: 3')
df.columns = df.iloc[0]
df = df.drop('Market year*')
df = df.sort_index(ascending = True)
df.index.name, df.columns.name = None, None
df = df.stack()
dates = [(month + '-' + year) for year, month in df.index.values]
df.index = pd.to_datetime(dates)
df = df.to_frame(name = "Avocados imported by the US (KG-TONS)")
df.index.name = 'Month'

In [2]:
# Avocados imported by the US

df = df * poundsToKg
df

           Avocados imported by the US (KG-TONS)
Month
2017-01-01                          97218.246698
2017-02-01                          71648.114556
2017-03-01                          77750.695578
2017-04-01                          70743.772294
2017-05-01                           65170.14584
2017-06-01                          74921.879885
2017-07-01                          63543.500167
2017-08-01                           63784.97197
2017-09-01                          71726.376492
2017-10-01                          79998.895744
2017-11-01                          77021.634173
2017-12-01                          86669.039303
2018-01-01                          98266.394843
2018-02-01                          83628.088784
2018-03-01                          91985.644966
2018-04-01                          89368.496101
2018-05-01                          77877.468474
2018-06-01                          81328.569659
2018-07-01                          80288.361508
2018-08-01                          90106.485499
2018-09-01                          80490.325343
2018-10-01                          90063.916534
2018-11-01                          80097.499664
2018-12-01                          94295.554082
2019-01-01                         123432.979314
2019-02-01                          95193.652349
2019-03-01                         109041.950053
2019-04-01                          94033.216296
2019-05-01                          81114.920834
2019-06-01                          58670.125142
2019-07-01                          88289.866981
2019-08-01                          77763.535567
2019-09-01                          91695.778203
2019-10-01                          100379.00012
2019-11-01                          88862.545514
2019-12-01                          96712.380111
2020-01-01                           121244.4351
2020-02-01                           84048.92044
2020-03-01                           82075.41405
2020-04-01                          73068.713397
2020-05-01                           83865.20559
2020-06-01                          95927.162751
2020-07-01                          93900.425404
2020-08-01                          87103.297949
2020-09-01                          89757.059784
2020-10-01                         107899.563985
2020-11-01                          97131.071769
2020-12-01                          100476.90904
2021-01-01                         134867.586987
2021-02-01                         100151.995305
2021-03-01                         115928.335436
2021-04-01                           93035.41211
2021-05-01                          90403.115257
2021-06-01                          98109.877971

In [3]:
# Avocados exported by Mexico to the US (KG-TONS)

df.columns.values[0] = "Avocados exported by Mexico to the US (KG-TONS)"
df = df * shareMexico
df

           Avocados exported by Mexico to the US (KG-TONS)
Month
2017-01-01                                    86329.803068
2017-02-01                                    63623.525726
2017-03-01                                    69042.617673
2017-04-01                                    62820.469797
2017-05-01                                    57871.089506
2017-06-01                                    66530.629338
2017-07-01                                    56426.628148
2017-08-01                                    56641.055109
2017-09-01                                    63693.022325
2017-10-01                                    71039.019421
2017-11-01                                    68395.211145
2017-12-01                                    76962.106901
2018-01-01                                    87260.558621
2018-02-01                                     74261.74284
2018-03-01                                     81683.25273
2018-04-01                                    79359.224538
2018-05-01                                    69155.192005
2018-06-01                                    72219.769858
2018-07-01                                    71296.065019
2018-08-01                                    80014.559123
2018-09-01                                    71475.408905
2018-10-01                                    79976.757882
2018-11-01                                    71126.579701
2018-12-01                                    83734.452025
2019-01-01                                   109608.485631
2019-02-01                                    84531.963286
2019-03-01                                    96829.251647
2019-04-01                                    83501.496071
2019-05-01                                      72030.0497
2019-06-01                                    52099.071126
2019-07-01                                    78401.401879
2019-08-01                                    69054.019584
2019-09-01                                    81425.851044
2019-10-01                                    89136.552106
2019-11-01                                    78909.940416
2019-12-01                                    85880.593538
2020-01-01                                   107665.058368
2020-02-01                                    74635.441351
2020-03-01                                    72882.967677
2020-04-01                                    64885.017497
2020-05-01                                    74472.302564
2020-06-01                                    85183.320523
2020-07-01                                    83383.577759
2020-08-01                                    77347.728579
2020-09-01                                    79704.269088
2020-10-01                                    95814.812819
2020-11-01                                    86252.391731
2020-12-01                                    89223.495227
2021-01-01                                   119762.417244
2021-02-01                                    88934.971831
2021-03-01                                   102944.361867
2021-04-01                                    82615.445954
2021-05-01                                    80277.966348
2021-06-01                                    87121.571638